// Auto-generated commercial drug formulation map. Generic name -> {use, brands}
// Brand examples are illustrative across global markets (US/EU/India); availability varies by region.
export interface DrugFormulation { use: string; brands: string[]; }
export const DRUG_FORMULATIONS: Record<string, DrugFormulation> = {
  "Paracetamol": { use: "Mild-moderate pain, fever", brands: ["Tylenol", "Panadol", "Calpol", "Crocin", "Dolo 650", "Acamol", "Mexalen", "Tachipirina", "Adol", "Fevadol", "Perfalgan"] },
  "Ibuprofen": { use: "Pain, fever, inflammation", brands: ["Advil", "Motrin", "Brufen", "Nurofen", "Combiflam", "Ibugesic", "Saridon Advance"] },
  "Aspirin": { use: "Antiplatelet, analgesic", brands: ["Disprin", "Ecosprin", "Bayer Aspirin", "Bufferin", "Aspro", "Anacin"] },
  "Naproxen": { use: "Pain, inflammation, arthritis", brands: ["Aleve", "Naprosyn", "Anaprox", "Naprelan", "Naprogesic"] },
  "Diclofenac": { use: "NSAID for pain & inflammation", brands: ["Voltaren", "Voveran", "Cataflam", "Diclomax", "Dynapar", "Zorvolex"] },
  "Celecoxib": { use: "COX-2 selective NSAID", brands: ["Celebrex", "Celebra", "Onsenal", "Colcibra"] },
  "Meloxicam": { use: "Osteoarthritis, rheumatoid arthritis", brands: ["Mobic", "Movalis", "Melox", "Muvera", "Mobicox"] },
  "Indomethacin": { use: "Acute gout, arthritis", brands: ["Indocin", "Indocid", "Tivorbex", "Microcid"] },
  "Piroxicam": { use: "Arthritis pain", brands: ["Feldene", "Brexin", "Dolonex"] },
  "Ketorolac": { use: "Short-term acute pain", brands: ["Toradol", "Acular", "Sprix", "Ketolac"] },
  "Mefenamic Acid": { use: "Dysmenorrhea, mild pain", brands: ["Ponstan", "Meftal", "Ponstel", "Dysman"] },
  "Tramadol": { use: "Moderate-severe pain", brands: ["Ultram", "Tramal", "Contramal", "Tramacip", "Zydol"] },
  "Morphine": { use: "Severe pain", brands: ["MS Contin", "Morcontin", "Kadian", "Roxanol", "Avinza", "Sevredol"] },
  "Codeine": { use: "Mild-moderate pain, cough", brands: ["Codeine Sulfate", "Tylenol with Codeine", "Codiprex"] },
  "Fentanyl": { use: "Severe pain, anesthesia", brands: ["Duragesic", "Sublimaze", "Actiq", "Fentora", "Abstral"] },
  "Oxycodone": { use: "Moderate-severe pain", brands: ["OxyContin", "Percocet", "Roxicodone", "Endone", "Oxynorm"] },
  "Hydrocodone": { use: "Moderate-severe pain, cough", brands: ["Vicodin", "Norco", "Lortab", "Hysingla ER"] },
  "Methadone": { use: "Opioid dependence, chronic pain", brands: ["Dolophine", "Methadose", "Physeptone"] },
  "Buprenorphine": { use: "Opioid dependence, pain", brands: ["Subutex", "Suboxone", "Belbuca", "Butrans", "Temgesic"] },
  "Pethidine": { use: "Acute pain (peri-operative)", brands: ["Demerol", "Petidin Sopharma"] },
  "Tapentadol": { use: "Moderate-severe pain", brands: ["Nucynta", "Palexia", "Tapal", "Tydol"] },
  "Warfarin": { use: "Anticoagulant for AF, VTE", brands: ["Coumadin", "Jantoven", "Marevan", "Warf", "Uniwarfin"] },
  "Clopidogrel": { use: "Antiplatelet post-ACS, stroke", brands: ["Plavix", "Clopilet", "Clopivas", "Deplatt", "Iscover"] },
  "Heparin": { use: "Acute anticoagulation", brands: ["Heparin Sodium", "Hep-Lock", "Calciparine"] },
  "Enoxaparin": { use: "LMWH for VTE prophylaxis/treatment", brands: ["Lovenox", "Clexane", "Klexane", "Enoxaparin Sodium"] },
  "Rivaroxaban": { use: "DOAC for AF, VTE", brands: ["Xarelto"] },
  "Apixaban": { use: "DOAC for AF, VTE", brands: ["Eliquis"] },
  "Dabigatran": { use: "DOAC for AF, VTE", brands: ["Pradaxa", "Pradax"] },
  "Ticagrelor": { use: "Antiplatelet for ACS", brands: ["Brilinta", "Brilique"] },
  "Prasugrel": { use: "Antiplatelet for ACS with PCI", brands: ["Effient", "Efient"] },
  "Fondaparinux": { use: "VTE prophylaxis", brands: ["Arixtra"] },
  "Atorvastatin": { use: "Lipid-lowering (statin)", brands: ["Lipitor", "Atorlip", "Atorva", "Storvas", "Sortis", "Tahor"] },
  "Simvastatin": { use: "Lipid-lowering (statin)", brands: ["Zocor", "Simlup", "Simvotin", "Lipex"] },
  "Rosuvastatin": { use: "Lipid-lowering (statin)", brands: ["Crestor", "Rosuvas", "Razel", "Rozavel"] },
  "Pravastatin": { use: "Lipid-lowering (statin)", brands: ["Pravachol", "Lipostat", "Pravator"] },
  "Fluvastatin": { use: "Lipid-lowering (statin)", brands: ["Lescol", "Canef", "Locol"] },
  "Lovastatin": { use: "Lipid-lowering (statin)", brands: ["Mevacor", "Altocor", "Lovacard"] },
  "Pitavastatin": { use: "Lipid-lowering (statin)", brands: ["Livalo", "Livazo", "Pitava"] },
  "Ezetimibe": { use: "Cholesterol absorption inhibitor", brands: ["Zetia", "Ezetrol", "Ezedoc"] },
  "Fenofibrate": { use: "Hypertriglyceridemia", brands: ["Tricor", "Lipidil", "Lipofen", "Fenoglide"] },
  "Gemfibrozil": { use: "Hypertriglyceridemia", brands: ["Lopid", "Gemcor", "Jezil"] },
  "Metformin": { use: "Type 2 diabetes mellitus", brands: ["Glucophage", "Glycomet", "Fortamet", "Riomet", "Diabex", "Obimet"] },
  "Insulin": { use: "Diabetes mellitus", brands: ["Humalog", "Novolog", "Lantus", "Levemir", "Tresiba", "Toujeo", "Humulin", "Novolin", "Apidra"] },
  "Glimepiride": { use: "Type 2 diabetes (sulfonylurea)", brands: ["Amaryl", "Glimer", "Glimy", "Diapride"] },
  "Glipizide": { use: "Type 2 diabetes (sulfonylurea)", brands: ["Glucotrol", "Minidiab", "Glynase"] },
  "Glyburide": { use: "Type 2 diabetes (sulfonylurea)", brands: ["DiaBeta", "Glynase", "Micronase", "Daonil"] },
  "Pioglitazone": { use: "Type 2 diabetes (TZD)", brands: ["Actos", "Pioz", "Pioglar", "Glustin"] },
  "Sitagliptin": { use: "Type 2 diabetes (DPP-4)", brands: ["Januvia", "Janumet", "Istavel", "Zituvio"] },
  "Empagliflozin": { use: "Type 2 diabetes, HF (SGLT2)", brands: ["Jardiance", "Synjardy", "Glyxambi"] },
  "Dapagliflozin": { use: "Type 2 diabetes, HF, CKD", brands: ["Farxiga", "Forxiga", "Xigduo"] },
  "Canagliflozin": { use: "Type 2 diabetes (SGLT2)", brands: ["Invokana", "Invokamet"] },
  "Liraglutide": { use: "Type 2 diabetes, obesity (GLP-1)", brands: ["Victoza", "Saxenda"] },
  "Semaglutide": { use: "Type 2 diabetes, obesity (GLP-1)", brands: ["Ozempic", "Wegovy", "Rybelsus"] },
  "Exenatide": { use: "Type 2 diabetes (GLP-1)", brands: ["Byetta", "Bydureon"] },
  "Repaglinide": { use: "Type 2 diabetes (meglitinide)", brands: ["Prandin", "NovoNorm", "Repa"] },
  "Acarbose": { use: "Type 2 diabetes (alpha-glucosidase)", brands: ["Precose", "Glucobay", "Glubose"] },
  "Amoxicillin": { use: "Bacterial infections (penicillin)", brands: ["Amoxil", "Moxikind", "Novamox", "Mox", "Trimox", "Wymox"] },
  "Ampicillin": { use: "Bacterial infections (penicillin)", brands: ["Principen", "Omnipen", "Ampilin", "Roscillin"] },
  "Amoxicillin-Clavulanate": { use: "Beta-lactam + inhibitor", brands: ["Augmentin", "Clavam", "Moxiclav", "Co-Amoxiclav", "Curam"] },
  "Piperacillin-Tazobactam": { use: "Severe hospital infections", brands: ["Zosyn", "Tazocin", "Zostum", "Piptaz"] },
  "Cephalexin": { use: "Skin & soft tissue infections", brands: ["Keflex", "Cefovit", "Sporidex", "Phexin"] },
  "Cefuroxime": { use: "Respiratory & UTI infections", brands: ["Ceftin", "Zinacef", "Pulmocef", "Ceroxim"] },
  "Ceftriaxone": { use: "Severe bacterial infections (IV)", brands: ["Rocephin", "Monocef", "Ceftrix", "Oframax"] },
  "Cefixime": { use: "Oral cephalosporin for URI/UTI", brands: ["Suprax", "Taxim-O", "Zifi", "Cefolac"] },
  "Ceftazidime": { use: "Pseudomonal infections", brands: ["Fortaz", "Tazicef", "Tazidime", "Tazid"] },
  "Cefepime": { use: "Broad-spectrum hospital infections", brands: ["Maxipime", "Voco", "Forpar"] },
  "Azithromycin": { use: "Macrolide for RTI, STI", brands: ["Zithromax", "Z-Pak", "Azithral", "Azee", "Zmax"] },
  "Clarithromycin": { use: "Macrolide for RTI, H.pylori", brands: ["Biaxin", "Klacid", "Crixan", "Claribid"] },
  "Erythromycin": { use: "Macrolide for various infections", brands: ["Erythrocin", "E-Mycin", "Ery-Tab", "Althrocin"] },
  "Ciprofloxacin": { use: "Fluoroquinolone broad spectrum", brands: ["Cipro", "Ciplox", "Ciprobay", "Cifran"] },
  "Levofloxacin": { use: "Fluoroquinolone for RTI/UTI", brands: ["Levaquin", "Tavanic", "Levoflox", "Levant"] },
  "Moxifloxacin": { use: "Respiratory fluoroquinolone", brands: ["Avelox", "Vigamox", "Moxif", "Mflox"] },
  "Norfloxacin": { use: "UTI, GI infections", brands: ["Noroxin", "Norflox", "Norbactin"] },
  "Ofloxacin": { use: "Broad-spectrum fluoroquinolone", brands: ["Floxin", "Oflox", "Tarivid", "Zanocin"] },
  "Doxycycline": { use: "Tetracycline for various infections", brands: ["Vibramycin", "Doryx", "Doxin", "Minicycline"] },
  "Tetracycline": { use: "Broad-spectrum antibiotic", brands: ["Sumycin", "Achromycin", "Resteclin"] },
  "Minocycline": { use: "Acne, skin infections", brands: ["Minocin", "Solodyn", "Dynacin"] },
  "Clindamycin": { use: "Anaerobic & skin infections", brands: ["Cleocin", "Dalacin", "Clindac-A", "Clinwas"] },
  "Metronidazole": { use: "Anaerobic & protozoal infections", brands: ["Flagyl", "Metrogyl", "Metrogel", "Aristogyl"] },
  "Trimethoprim-Sulfamethoxazole": { use: "UTI, PCP prophylaxis", brands: ["Bactrim", "Septra", "Septran", "Cotrim"] },
  "Vancomycin": { use: "MRSA, severe Gram-positive", brands: ["Vancocin", "Vanlid", "Vancomax"] },
  "Linezolid": { use: "Resistant Gram-positive infections", brands: ["Zyvox", "Linospan", "Lizolid"] },
  "Nitrofurantoin": { use: "Uncomplicated UTI", brands: ["Macrobid", "Macrodantin", "Nitrofur", "Niftran"] },
  "Gentamicin": { use: "Aminoglycoside for Gram-negative", brands: ["Garamycin", "Genticyn", "Cidomycin"] },
  "Amikacin": { use: "Aminoglycoside for resistant infections", brands: ["Amikin", "Mikacin", "Selemycin"] },
  "Tobramycin": { use: "Aminoglycoside, cystic fibrosis", brands: ["Tobi", "Bethkis", "Tobrex"] },
  "Fluconazole": { use: "Antifungal for candidiasis", brands: ["Diflucan", "Forcan", "Fluc", "Syscan"] },
  "Ketoconazole": { use: "Antifungal (topical/systemic)", brands: ["Nizoral", "Ketovate", "Ketoderm"] },
  "Itraconazole": { use: "Systemic antifungal", brands: ["Sporanox", "Itracap", "Canditral"] },
  "Voriconazole": { use: "Invasive aspergillosis", brands: ["Vfend", "Voritop", "Vorier"] },
  "Posaconazole": { use: "Invasive fungal prophylaxis", brands: ["Noxafil", "Posanol"] },
  "Terbinafine": { use: "Onychomycosis, tinea", brands: ["Lamisil", "Terbicip", "Daskil"] },
  "Nystatin": { use: "Topical/oral candidiasis", brands: ["Mycostatin", "Nystop", "Nilstat"] },
  "Amphotericin B": { use: "Severe systemic mycoses", brands: ["Fungizone", "Ambisome", "Abelcet"] },
  "Caspofungin": { use: "Invasive candidiasis (echinocandin)", brands: ["Cancidas"] },
  "Micafungin": { use: "Invasive candidiasis (echinocandin)", brands: ["Mycamine", "Funguard"] },
  "Acyclovir": { use: "Herpes simplex/zoster", brands: ["Zovirax", "Acivir", "Cyclovir"] },
  "Valacyclovir": { use: "HSV, VZV antiviral", brands: ["Valtrex", "Valcivir", "Vacirex"] },
  "Oseltamivir": { use: "Influenza A/B", brands: ["Tamiflu", "Fluvir", "Antiflu"] },
  "Remdesivir": { use: "COVID-19 antiviral", brands: ["Veklury", "Covifor", "Cipremi"] },
  "Ritonavir": { use: "HIV protease inhibitor / booster", brands: ["Norvir", "Ritomune"] },
  "Lopinavir": { use: "HIV protease inhibitor", brands: ["Kaletra", "Aluvia"] },
  "Tenofovir": { use: "HIV/HBV NRTI", brands: ["Viread", "Tenof", "Tafero"] },
  "Emtricitabine": { use: "HIV NRTI", brands: ["Emtriva", "Emcitra"] },
  "Dolutegravir": { use: "HIV integrase inhibitor", brands: ["Tivicay", "Dolegra"] },
  "Efavirenz": { use: "HIV NNRTI", brands: ["Sustiva", "Stocrin", "Efavir"] },
  "Omeprazole": { use: "PPI for GERD, ulcers", brands: ["Prilosec", "Omez", "Losec", "Ocid", "Zegerid"] },
  "Pantoprazole": { use: "PPI for GERD, ulcers", brands: ["Protonix", "Pantocid", "Pan", "Pantop"] },
  "Esomeprazole": { use: "PPI for GERD", brands: ["Nexium", "Esoz", "Sompraz", "Nexpro"] },
  "Lansoprazole": { use: "PPI for GERD, ulcers", brands: ["Prevacid", "Lanzol", "Junior Prevacid"] },
  "Rabeprazole": { use: "PPI for GERD", brands: ["AcipHex", "Rabicip", "Razo", "Rablet"] },
  "Ranitidine": { use: "H2 blocker for acid reduction (limited use)", brands: ["Zantac", "Aciloc", "Rantac"] },
  "Famotidine": { use: "H2 blocker for GERD", brands: ["Pepcid", "Famocid", "Famtac", "Topcid"] },
  "Cimetidine": { use: "H2 blocker (older agent)", brands: ["Tagamet", "Cimet"] },
  "Sucralfate": { use: "Mucosal protectant for ulcers", brands: ["Carafate", "Sucral", "Sucrace"] },
  "Misoprostol": { use: "NSAID ulcer prevention", brands: ["Cytotec", "Misoprost"] },
  "Ondansetron": { use: "Antiemetic (5-HT3 antagonist)", brands: ["Zofran", "Emeset", "Vomikind", "Ondem"] },
  "Metoclopramide": { use: "Prokinetic antiemetic", brands: ["Reglan", "Perinorm", "Maxolon"] },
  "Domperidone": { use: "Prokinetic antiemetic", brands: ["Motilium", "Domstal", "Vomistop"] },
  "Loperamide": { use: "Acute diarrhea", brands: ["Imodium", "Lopamide", "Eldoper"] },
  "Diazepam": { use: "Anxiety, seizures, muscle spasm", brands: ["Valium", "Calmpose", "Diazep", "Stesolid"] },
  "Alprazolam": { use: "Anxiety, panic disorder", brands: ["Xanax", "Alprax", "Restyl", "Trika"] },
  "Lorazepam": { use: "Anxiety, status epilepticus", brands: ["Ativan", "Lopez", "Trapex"] },
  "Clonazepam": { use: "Seizures, panic disorder", brands: ["Klonopin", "Rivotril", "Clonotril"] },
  "Midazolam": { use: "Procedural sedation, status epilepticus", brands: ["Versed", "Dormicum", "Hypnogen"] },
  "Sertraline": { use: "SSRI for depression, OCD, PTSD", brands: ["Zoloft", "Daxid", "Serlift", "Lustral"] },
  "Fluoxetine": { use: "SSRI for depression, OCD", brands: ["Prozac", "Sarafem", "Fludac", "Flunil"] },
  "Citalopram": { use: "SSRI for depression", brands: ["Celexa", "Cipramil", "Talam"] },
  "Escitalopram": { use: "SSRI for depression, GAD", brands: ["Lexapro", "Cipralex", "Nexito", "S-Citadep"] },
  "Paroxetine": { use: "SSRI for depression, anxiety", brands: ["Paxil", "Seroxat", "Pari", "Xet"] },
  "Fluvoxamine": { use: "SSRI for OCD", brands: ["Luvox", "Faverin", "Fluvoxin"] },
  "Venlafaxine": { use: "SNRI for depression", brands: ["Effexor", "Venlor", "Veniz"] },
  "Duloxetine": { use: "SNRI for depression, neuropathic pain", brands: ["Cymbalta", "Duzela", "Dulane"] },
  "Amitriptyline": { use: "TCA for depression, neuropathic pain", brands: ["Elavil", "Tryptomer", "Amitone"] },
  "Nortriptyline": { use: "TCA for depression, neuropathic pain", brands: ["Pamelor", "Sensival", "Primox"] },
  "Bupropion": { use: "Atypical antidepressant; smoking cessation", brands: ["Wellbutrin", "Zyban", "Bupron"] },
  "Mirtazapine": { use: "Atypical antidepressant", brands: ["Remeron", "Mirt", "Mirtaz"] },
  "Trazodone": { use: "Depression, insomnia", brands: ["Desyrel", "Trazonil", "Trazalon"] },
  "Haloperidol": { use: "Typical antipsychotic", brands: ["Haldol", "Serenace", "Halo"] },
  "Risperidone": { use: "Atypical antipsychotic", brands: ["Risperdal", "Risdone", "Sizodon"] },
  "Olanzapine": { use: "Atypical antipsychotic", brands: ["Zyprexa", "Oleanz", "Olexar"] },
  "Quetiapine": { use: "Atypical antipsychotic, bipolar", brands: ["Seroquel", "Qutipin", "Q-Pin"] },
  "Aripiprazole": { use: "Atypical antipsychotic", brands: ["Abilify", "Arip MT", "Asprito"] },
  "Clozapine": { use: "Refractory schizophrenia", brands: ["Clozaril", "Sizopin", "Clonex"] },
  "Ziprasidone": { use: "Atypical antipsychotic", brands: ["Geodon", "Zeldox"] },
  "Lithium": { use: "Bipolar disorder mood stabilizer", brands: ["Lithobid", "Eskalith", "Licab", "Lithosun"] },
  "Valproic Acid": { use: "Seizures, bipolar disorder", brands: ["Depakote", "Depakene", "Encorate", "Valparin"] },
  "Phenytoin": { use: "Seizures (sodium channel blocker)", brands: ["Dilantin", "Eptoin", "Phenytoin Sodium"] },
  "Carbamazepine": { use: "Seizures, trigeminal neuralgia", brands: ["Tegretol", "Mazetol", "Zen", "Zeptol"] },
  "Lamotrigine": { use: "Seizures, bipolar", brands: ["Lamictal", "Lamitor", "Lametec"] },
  "Levetiracetam": { use: "Broad-spectrum antiepileptic", brands: ["Keppra", "Levipil", "Torleva"] },
  "Topiramate": { use: "Seizures, migraine prophylaxis", brands: ["Topamax", "Topamac", "Topirol"] },
  "Gabapentin": { use: "Neuropathic pain, partial seizures", brands: ["Neurontin", "Gabantin", "Gabapin"] },
  "Pregabalin": { use: "Neuropathic pain, GAD, seizures", brands: ["Lyrica", "Pregalin", "Maxgalin"] },
  "Lisinopril": { use: "ACE inhibitor for HTN, HF", brands: ["Prinivil", "Zestril", "Lisoril", "Listril"] },
  "Enalapril": { use: "ACE inhibitor for HTN, HF", brands: ["Vasotec", "Envas", "Enam", "Enapril"] },
  "Ramipril": { use: "ACE inhibitor for HTN, HF", brands: ["Altace", "Cardace", "Ramcor", "Tritace"] },
  "Captopril": { use: "ACE inhibitor for HTN", brands: ["Capoten", "Aceten"] },
  "Losartan": { use: "ARB for HTN, nephropathy", brands: ["Cozaar", "Repace", "Losar", "Tozaar"] },
  "Valsartan": { use: "ARB for HTN, HF", brands: ["Diovan", "Valzaar", "Starval"] },
  "Telmisartan": { use: "ARB for HTN", brands: ["Micardis", "Telma", "Telsartan"] },
  "Olmesartan": { use: "ARB for HTN", brands: ["Benicar", "Olmin", "Olmesar"] },
  "Propranolol": { use: "Non-selective beta-blocker", brands: ["Inderal", "Hemangeol", "Ciplar"] },
  "Atenolol": { use: "Selective beta-blocker for HTN", brands: ["Tenormin", "Aten", "Beten"] },
  "Metoprolol": { use: "Selective beta-blocker for HTN, HF", brands: ["Lopressor", "Toprol XL", "Metolar", "Betaloc"] },
  "Bisoprolol": { use: "Selective beta-blocker for HF, HTN", brands: ["Zebeta", "Concor", "Bisoheart"] },
  "Carvedilol": { use: "Alpha/beta blocker for HF, HTN", brands: ["Coreg", "Carca", "Cardivas", "Carvil"] },
  "Nebivolol": { use: "Cardioselective beta-blocker", brands: ["Bystolic", "Nebicard", "Nodon"] },
  "Labetalol": { use: "Alpha/beta blocker, pregnancy HTN", brands: ["Trandate", "Normodyne", "Lobet"] },
  "Sotalol": { use: "Antiarrhythmic + beta-blocker", brands: ["Betapace", "Sotalex", "Sotagard"] },
  "Amlodipine": { use: "CCB for HTN, angina", brands: ["Norvasc", "Amlong", "Amlogard", "Stamlo"] },
  "Nifedipine": { use: "CCB for HTN, angina", brands: ["Procardia", "Adalat", "Nicardia", "Calcigard"] },
  "Diltiazem": { use: "CCB for HTN, arrhythmias", brands: ["Cardizem", "Tildiem", "Dilzem", "Angizem"] },
  "Verapamil": { use: "CCB for arrhythmias, HTN", brands: ["Calan", "Isoptin", "Verelan", "Calaptin"] },
  "Felodipine": { use: "CCB for HTN", brands: ["Plendil", "Felogard", "Renedil"] },
  "Digoxin": { use: "HF, AF rate control", brands: ["Lanoxin", "Digitek", "Cardioxin"] },
  "Amiodarone": { use: "Refractory ventricular arrhythmias", brands: ["Cordarone", "Pacerone", "Cordarex", "Tachyra"] },
  "Dronedarone": { use: "AF maintenance", brands: ["Multaq"] },
  "Furosemide": { use: "Loop diuretic for edema, HF", brands: ["Lasix", "Frusenex", "Diural"] },
  "Hydrochlorothiazide": { use: "Thiazide diuretic for HTN", brands: ["Microzide", "Esidrix", "HCZ"] },
  "Chlorthalidone": { use: "Thiazide-like diuretic for HTN", brands: ["Thalitone", "Hygroton", "Ctd"] },
  "Indapamide": { use: "Thiazide-like diuretic for HTN", brands: ["Lozol", "Natrilix", "Indicontin"] },
  "Spironolactone": { use: "K-sparing diuretic for HF, ascites", brands: ["Aldactone", "Spiractin", "Aldactazide"] },
  "Eplerenone": { use: "Mineralocorticoid antagonist for HF", brands: ["Inspra"] },
  "Bumetanide": { use: "Loop diuretic", brands: ["Bumex", "Burinex"] },
  "Torsemide": { use: "Loop diuretic for HF", brands: ["Demadex", "Toresma", "Dytor"] },
  "Prednisolone": { use: "Systemic corticosteroid", brands: ["Omnipred", "Pred Forte", "Wysolone"] },
  "Prednisone": { use: "Systemic corticosteroid", brands: ["Deltasone", "Rayos", "Sterapred"] },
  "Dexamethasone": { use: "Potent corticosteroid", brands: ["Decadron", "Dexona", "Wymesone"] },
  "Methylprednisolone": { use: "Corticosteroid, anti-inflammatory", brands: ["Medrol", "Solu-Medrol", "Depo-Medrol"] },
  "Hydrocortisone": { use: "Corticosteroid, adrenal replacement", brands: ["Cortef", "Solu-Cortef", "Cortaid"] },
  "Budesonide": { use: "Inhaled/oral corticosteroid", brands: ["Pulmicort", "Rhinocort", "Entocort", "Uceris"] },
  "Salbutamol": { use: "Short-acting beta-2 agonist", brands: ["Ventolin", "Proventil", "Asthalin", "Salbair"] },
  "Ipratropium": { use: "Anticholinergic bronchodilator", brands: ["Atrovent", "Ipravent"] },
  "Tiotropium": { use: "Long-acting anticholinergic for COPD", brands: ["Spiriva", "Tiova"] },
  "Formoterol": { use: "LABA bronchodilator", brands: ["Foradil", "Perforomist", "Symbicort (combo)"] },
  "Salmeterol": { use: "LABA bronchodilator", brands: ["Serevent", "Advair (combo)", "Seretide (combo)"] },
  "Montelukast": { use: "Leukotriene receptor antagonist", brands: ["Singulair", "Montair", "Montek"] },
  "Theophylline": { use: "Bronchodilator for asthma/COPD", brands: ["Theo-Dur", "Uniphyl", "Theobid"] },
  "Fluticasone": { use: "Inhaled corticosteroid", brands: ["Flovent", "Flixotide", "Cutivate", "Arnuity"] },
  "Levothyroxine": { use: "Hypothyroidism replacement", brands: ["Synthroid", "Eltroxin", "Levoxyl", "Thyronorm"] },
  "Methimazole": { use: "Hyperthyroidism (thionamide)", brands: ["Tapazole", "Thyrozol", "Mercazole"] },
  "Propylthiouracil": { use: "Hyperthyroidism, thyroid storm", brands: ["PTU", "Propyl-Thyracil"] },
  "Cetirizine": { use: "2nd-gen antihistamine for allergies", brands: ["Zyrtec", "Reactine", "Alerid", "Cetzine"] },
  "Loratadine": { use: "2nd-gen antihistamine", brands: ["Claritin", "Alavert", "Lorfast", "Lorinol"] },
  "Fexofenadine": { use: "2nd-gen antihistamine", brands: ["Allegra", "Telfast", "Fexova", "Allerfex"] },
  "Diphenhydramine": { use: "1st-gen antihistamine, sleep aid", brands: ["Benadryl", "Banophen", "Sominex"] },
  "Promethazine": { use: "1st-gen antihistamine, antiemetic", brands: ["Phenergan", "Phenadoz", "Avomine"] },
  "Cyclobenzaprine": { use: "Skeletal muscle relaxant", brands: ["Flexeril", "Amrix", "Fexmid"] },
  "Baclofen": { use: "Antispasmodic for MS, spinal injury", brands: ["Lioresal", "Liofen", "Gablofen"] },
  "Tizanidine": { use: "Muscle relaxant for spasticity", brands: ["Zanaflex", "Sirdalud", "Tizan"] },
  "Cyclosporine": { use: "Calcineurin inhibitor immunosuppressant", brands: ["Sandimmune", "Neoral", "Gengraf", "Restasis"] },
  "Tacrolimus": { use: "Calcineurin inhibitor for transplant", brands: ["Prograf", "Protopic", "Advagraf", "Pangraf"] },
  "Mycophenolate": { use: "Antiproliferative immunosuppressant", brands: ["CellCept", "Myfortic", "Mycept"] },
  "Azathioprine": { use: "Purine antimetabolite immunosuppressant", brands: ["Imuran", "Azoran", "Immuran"] },
  "Methotrexate": { use: "DMARD; chemotherapy", brands: ["Trexall", "Otrexup", "Rasuvo", "Folitrax"] },
  "Hydroxychloroquine": { use: "DMARD; malaria", brands: ["Plaquenil", "HCQS", "Hcqtor"] },
  "Sulfasalazine": { use: "IBD, RA", brands: ["Azulfidine", "Saaz", "Sazo"] },
  "Allopurinol": { use: "Chronic gout (xanthine oxidase inhibitor)", brands: ["Zyloprim", "Aloprim", "Zyloric"] },
  "Colchicine": { use: "Acute gout, FMF", brands: ["Colcrys", "Mitigare", "Goutnil"] },
  "Febuxostat": { use: "Chronic gout", brands: ["Uloric", "Feburic", "Febutaz"] },
  "Alendronate": { use: "Osteoporosis (bisphosphonate)", brands: ["Fosamax", "Binosto", "Restofos"] },
  "Risedronate": { use: "Osteoporosis (bisphosphonate)", brands: ["Actonel", "Atelvia", "Risofos"] },
  "Zoledronic Acid": { use: "Osteoporosis, hypercalcemia", brands: ["Reclast", "Zometa", "Zoldonat"] },
  "Tamsulosin": { use: "BPH (alpha-1 blocker)", brands: ["Flomax", "Urimax", "Tamlet"] },
  "Finasteride": { use: "BPH, androgenic alopecia", brands: ["Proscar", "Propecia", "Finpecia", "Fincar"] },
  "Dutasteride": { use: "BPH (5-alpha reductase)", brands: ["Avodart", "Dutas", "Veltam"] },
  "Sildenafil": { use: "ED, pulmonary hypertension", brands: ["Viagra", "Revatio", "Suhagra", "Penegra"] },
  "Tadalafil": { use: "ED, BPH, PAH", brands: ["Cialis", "Adcirca", "Tadacip", "Megalis"] },
  "Oxybutynin": { use: "Overactive bladder", brands: ["Ditropan", "Oxytrol", "Oxybutin"] },
  "Tolterodine": { use: "Overactive bladder", brands: ["Detrol", "Detrusitol", "Roliten"] },
  "Solifenacin": { use: "Overactive bladder", brands: ["Vesicare", "Vesi"] },
  "Rifampicin": { use: "Antitubercular (rifamycin)", brands: ["Rifadin", "Rimactane", "R-Cin", "Rifater"] },
  "Isoniazid": { use: "Antitubercular", brands: ["Nydrazid", "INH", "Isokin"] },
  "Pyrazinamide": { use: "Antitubercular", brands: ["PZA", "Pyrazide", "Macrozide"] },
  "Ethambutol": { use: "Antitubercular", brands: ["Myambutol", "Themibutol", "Combutol"] },
  "Naloxone": { use: "Opioid overdose reversal", brands: ["Narcan", "Evzio", "Kloxxado"] },
  "Naltrexone": { use: "Opioid/alcohol dependence", brands: ["Vivitrol", "ReVia", "Naltima"] },
  "Tamoxifen": { use: "ER+ breast cancer", brands: ["Nolvadex", "Soltamox", "Tamodex"] },
  "Letrozole": { use: "Aromatase inhibitor for breast cancer", brands: ["Femara", "Letoval", "Letros"] },
  "Anastrozole": { use: "Aromatase inhibitor for breast cancer", brands: ["Arimidex", "Anabrez", "Anozole"] },
  "Imatinib": { use: "CML, GIST (TKI)", brands: ["Gleevec", "Glivec", "Imatib"] },
  "Ivermectin": { use: "Antiparasitic (strongyloides, scabies)", brands: ["Stromectol", "Sklice", "Iverwon", "Ivecop"] },
  "Albendazole": { use: "Antihelminthic", brands: ["Albenza", "Zentel", "Bandy"] },
  "Mebendazole": { use: "Antihelminthic", brands: ["Vermox", "Emverm", "Wormin"] },
  "Isotretinoin": { use: "Severe nodulocystic acne (retinoid)", brands: ["Accutane", "Claravis", "Sotret", "Isotroin"] },
  "Zolpidem": { use: "Short-term insomnia", brands: ["Ambien", "Intermezzo", "Zolpid", "Stilnoct"] },
  "Eszopiclone": { use: "Insomnia", brands: ["Lunesta", "Eszest"] },
  "Sumatriptan": { use: "Acute migraine (triptan)", brands: ["Imitrex", "Imigran", "Suminat"] },
  "Rizatriptan": { use: "Acute migraine (triptan)", brands: ["Maxalt", "Rizact", "Rizora"] },
  "Timolol": { use: "Glaucoma (topical beta-blocker)", brands: ["Timoptic", "Betimol", "Glucomol"] },
  "Latanoprost": { use: "Glaucoma (prostaglandin analog)", brands: ["Xalatan", "Latim", "Latoprost"] },
  "Pseudoephedrine": { use: "Nasal decongestant", brands: ["Sudafed", "Suphedrin", "Nucofed"] },
  "Phenylephrine": { use: "Nasal decongestant", brands: ["Sudafed PE", "Neo-Synephrine"] },
  "Atropine": { use: "Bradycardia, organophosphate poisoning", brands: ["AtroPen", "Atnaa"] },
  "Epinephrine": { use: "Anaphylaxis, cardiac arrest", brands: ["EpiPen", "Adrenaclick", "Auvi-Q", "Adrenalin"] },
  "Donepezil": { use: "Alzheimer's disease (cholinesterase inhibitor)", brands: ["Aricept", "Donamem", "Donep"] },
  "Memantine": { use: "Moderate-severe Alzheimer's", brands: ["Namenda", "Admenta", "Memorit"] },
  "Rivastigmine": { use: "Alzheimer's, Parkinson dementia", brands: ["Exelon", "Rivasmine", "Rivamer"] },
  "Levodopa-Carbidopa": { use: "Parkinson disease", brands: ["Sinemet", "Rytary", "Duopa", "Syndopa"] },
  "Pramipexole": { use: "Parkinson disease, RLS", brands: ["Mirapex", "Sifrol", "Pramirol"] },
  "Ropinirole": { use: "Parkinson disease, RLS", brands: ["Requip", "Ropark", "Ropitor"] },
  "Clonidine": { use: "HTN, ADHD, opioid withdrawal", brands: ["Catapres", "Kapvay", "Arkamin"] },
  "Methyldopa": { use: "HTN in pregnancy", brands: ["Aldomet", "Emdopa"] },
  "Prazosin": { use: "HTN, PTSD nightmares", brands: ["Minipress", "Prazopress"] },
  "Doxazosin": { use: "HTN, BPH", brands: ["Cardura", "Doxacard"] },
  "Terazosin": { use: "HTN, BPH", brands: ["Hytrin", "Hytrin BPH", "Olyster"] },
  "Sorafenib": { use: "HCC, RCC (TKI)", brands: ["Nexavar", "Soranib"] },
  "Sunitinib": { use: "RCC, GIST (TKI)", brands: ["Sutent", "Sunitix"] },
  "Pazopanib": { use: "RCC, soft tissue sarcoma (TKI)", brands: ["Votrient", "Pazonib"] },
  "Lapatinib": { use: "HER2+ breast cancer (TKI)", brands: ["Tykerb", "Tyverb"] },
  "Crizotinib": { use: "ALK+ NSCLC (TKI)", brands: ["Xalkori", "Crizalk"] },
  "Vemurafenib": { use: "BRAF V600E melanoma", brands: ["Zelboraf"] },
  "Ibrutinib": { use: "CLL, MCL (BTK inhibitor)", brands: ["Imbruvica"] },
  "Palbociclib": { use: "HR+ breast cancer (CDK4/6)", brands: ["Ibrance", "Palbace"] },
  "Ribociclib": { use: "HR+ breast cancer (CDK4/6)", brands: ["Kisqali"] },
  "Osimertinib": { use: "EGFR+ NSCLC (TKI)", brands: ["Tagrisso", "Osicent"] },
  "Cisplatin": { use: "Platinum chemotherapy", brands: ["Platinol", "Cisplat"] },
  "Carboplatin": { use: "Platinum chemotherapy", brands: ["Paraplatin", "Carbocel"] },
  "Cyclophosphamide": { use: "Alkylating chemotherapy", brands: ["Cytoxan", "Endoxan", "Procytox"] },
  "Doxorubicin": { use: "Anthracycline chemotherapy", brands: ["Adriamycin", "Doxil", "Caelyx"] },
  "Paclitaxel": { use: "Taxane chemotherapy", brands: ["Taxol", "Abraxane", "Onxol"] },
  "Docetaxel": { use: "Taxane chemotherapy", brands: ["Taxotere", "Docefrez", "Daxotel"] },
  "Fluorouracil": { use: "Antimetabolite (5-FU) chemotherapy", brands: ["Adrucil", "Efudex", "Carac"] },
  "Capecitabine": { use: "Oral 5-FU prodrug", brands: ["Xeloda", "Capelta", "Xabine"] },
  "Gemcitabine": { use: "Antimetabolite chemotherapy", brands: ["Gemzar", "Gemcite", "Gemtaz"] },
  "Adalimumab": { use: "TNF-alpha inhibitor (RA, Crohn)", brands: ["Humira", "Exemptia", "Hyrimoz"] },
  "Infliximab": { use: "TNF-alpha inhibitor (IBD, RA)", brands: ["Remicade", "Inflectra", "Remsima"] },
  "Etanercept": { use: "TNF-alpha receptor (RA, psoriasis)", brands: ["Enbrel", "Erelzi", "Benepali"] },
  "Rituximab": { use: "Anti-CD20 mAb (lymphoma, RA)", brands: ["Rituxan", "MabThera", "Reditux"] },
  "Trastuzumab": { use: "HER2+ breast cancer mAb", brands: ["Herceptin", "Hertraz", "Trastrel"] },
  "Bevacizumab": { use: "Anti-VEGF mAb", brands: ["Avastin", "Mvasi", "Zirabev"] },
  "Cetuximab": { use: "EGFR mAb (CRC, H&N)", brands: ["Erbitux"] },
  "Nivolumab": { use: "PD-1 inhibitor (melanoma, NSCLC)", brands: ["Opdivo"] },
  "Pembrolizumab": { use: "PD-1 inhibitor (multiple cancers)", brands: ["Keytruda"] },
  "Linagliptin": { use: "Type 2 diabetes (DPP-4)", brands: ["Tradjenta", "Trajenta", "Lyumjev"] },
  "Saxagliptin": { use: "Type 2 diabetes (DPP-4)", brands: ["Onglyza"] },
  "Vildagliptin": { use: "Type 2 diabetes (DPP-4)", brands: ["Galvus", "Jalra"] },
  "Dulaglutide": { use: "Type 2 diabetes (GLP-1)", brands: ["Trulicity"] },
  "Tirzepatide": { use: "Type 2 diabetes, obesity (GIP/GLP-1)", brands: ["Mounjaro", "Zepbound"] },
  "Sofosbuvir": { use: "Hepatitis C antiviral", brands: ["Sovaldi", "Harvoni (combo)", "Epclusa (combo)"] },
  "Ledipasvir": { use: "Hepatitis C antiviral", brands: ["Harvoni (combo)"] },
  "Daclatasvir": { use: "Hepatitis C antiviral", brands: ["Daklinza"] },
  "Tranexamic Acid": { use: "Antifibrinolytic (bleeding)", brands: ["Lysteda", "Cyklokapron", "Tranexa"] },
  "Roflumilast": { use: "Severe COPD (PDE4 inhibitor)", brands: ["Daliresp", "Daxas"] },
  "Omalizumab": { use: "Severe allergic asthma (anti-IgE)", brands: ["Xolair"] },
  "Mesalamine": { use: "UC, Crohn's (5-ASA)", brands: ["Asacol", "Pentasa", "Lialda", "Apriso"] },
  "Lactulose": { use: "Constipation, hepatic encephalopathy", brands: ["Cephulac", "Kristalose", "Duphalac"] },
  "Mirabegron": { use: "Overactive bladder (beta-3 agonist)", brands: ["Myrbetriq", "Betmiga"] },
  "Vardenafil": { use: "ED (PDE5 inhibitor)", brands: ["Levitra", "Staxyn", "Vivanza"] },
  "Apremilast": { use: "Plaque psoriasis (PDE4)", brands: ["Otezla"] },
  "Tofacitinib": { use: "RA, UC, alopecia areata (JAK)", brands: ["Xeljanz"] },
  "Vortioxetine": { use: "Major depressive disorder", brands: ["Trintellix", "Brintellix"] },
  "Vilazodone": { use: "Depression (SSRI + 5-HT1A partial agonist)", brands: ["Viibryd"] },
  "Buspirone": { use: "GAD anxiolytic", brands: ["Buspar", "Buspin", "Anxiron"] },
  "Cariprazine": { use: "Schizophrenia, bipolar", brands: ["Vraylar", "Reagila"] },
  "Testosterone": { use: "Hypogonadism replacement", brands: ["AndroGel", "Testim", "Sustanon", "Depo-Testosterone"] },
  "Estradiol": { use: "Menopausal hormone therapy", brands: ["Estrace", "Climara", "Vivelle-Dot", "Divigel"] },
  "Progesterone": { use: "HRT, luteal support", brands: ["Prometrium", "Crinone", "Endometrin"] },
  "Leuprolide": { use: "GnRH agonist (prostate Ca, endometriosis)", brands: ["Lupron", "Eligard", "Lupride"] },
  "Goserelin": { use: "GnRH agonist (prostate, breast Ca)", brands: ["Zoladex"] },
  "Teriparatide": { use: "Severe osteoporosis (PTH analog)", brands: ["Forteo", "Bonsity"] },
  "Calcitonin": { use: "Hypercalcemia, osteoporosis", brands: ["Miacalcin", "Fortical"] },
  "Eltrombopag": { use: "ITP, severe aplastic anemia", brands: ["Promacta", "Revolade"] },
  "Hydroxyurea": { use: "Sickle cell, myeloproliferative", brands: ["Hydrea", "Droxia", "Siklos"] },
  "Filgrastim": { use: "Chemotherapy-induced neutropenia (G-CSF)", brands: ["Neupogen", "Zarxio", "Grafeel"] },
  "Pegfilgrastim": { use: "Long-acting G-CSF", brands: ["Neulasta", "Fulphila", "Udenyca"] },
  "Epoetin Alfa": { use: "Anemia of CKD/chemo (ESA)", brands: ["Epogen", "Procrit", "Eprex"] },
  "Abatacept": { use: "RA (T-cell co-stim modulator)", brands: ["Orencia"] },
  "Anakinra": { use: "RA, CAPS (IL-1 receptor antagonist)", brands: ["Kineret"] },
  "Tocilizumab": { use: "RA, GCA, CRS (IL-6 inhibitor)", brands: ["Actemra", "RoActemra"] },
  "Secukinumab": { use: "Psoriasis, AS (IL-17A inhibitor)", brands: ["Cosentyx"] },
  "Ustekinumab": { use: "Psoriasis, Crohn's, UC (IL-12/23)", brands: ["Stelara"] },
  "Dupilumab": { use: "Atopic dermatitis, asthma (IL-4R\u03b1)", brands: ["Dupixent"] },
  "Sacubitril-Valsartan": { use: "Chronic HFrEF (ARNI)", brands: ["Entresto", "Vymada"] },
  "Ivabradine": { use: "HF, stable angina (If channel blocker)", brands: ["Corlanor", "Procoralan", "Coralan"] },
  "Ranolazine": { use: "Chronic stable angina", brands: ["Ranexa", "Ranozex"] },
};
// Generic entries: 337 · Total brand formulations: 1048
export const FORMULATION_COUNT = 1048;
export const GENERIC_COUNT = 337;